# gitlab-runner exec shell build

#image: $CI_REGISTRY/buildroot.org/buildroot/base:20230207.1123

build:
  stage: build
  before_script:
    - apt-get update && apt-get install -y curl zstd
  script:
    - apt-get update
    - apt-get install -y bc rsync cpio
    - curl -s -L https://github.com/buildroot/buildroot/archive/refs/tags/2023.11.1.tar.gz | tar xvz
    - cd buildroot-2023.11.1
    - patch -p1 < ../buildroot.patch
    - make BR2_EXTERNAL=.. rgarc_defconfig
    - make
    - zstd buildroot-2023.11.1/output/images/brrrrrrrrrr-rgarc.img
  artifacts:
      paths:
        - buildroot-2023.11.1/output/images/brrrrrrrrrr-rgarc.img.zstd
  only:
    - master

create_release:
  stage: deploy
  script:
    - 'curl --header "Content-Type: application/json" --header "PRIVATE-TOKEN: $CI_JOB_TOKEN" --data "{ \"name\": \"Release $CI_COMMIT_REF_NAME\", \"tag_name\": \"$CI_COMMIT_REF_NAME\", \"description\": \"Release description here\", \"assets\": {\"links\": [{\"name\": \"brrrrrrrrrr-rgarc.img.zstd\", \"url\": \"${CI_PROJECT_URL}/-/jobs/${CI_JOB_ID}/artifacts/raw/buildroot-2023.11.1/output/images/brrrrrrrrrr-rgarc.img.zstd\"}]}}" "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/releases"'
  only:
    - tags
