#!/bin/bash

case "$1" in
    start)
        echo performance > /sys/devices/platform/fde60000.gpu/devfreq/fde60000.gpu/governor
        echo performance > /sys/devices/system/cpu/cpufreq/policy0/scaling_governor

	echo disabled > /sys/devices/platform/fdd40000.i2c/i2c-0/0-0020/rk817-charger.7.auto/power_supply/rk817-battery/power/wakeup
	echo disabled > /sys/devices/platform/fdd40000.i2c/i2c-0/0-0020/rk817-charger.7.auto/power_supply/rk817-charger/power/wakeup

        brightnessctl -r
        #amixer -q sset 'Playback Path' SPK
        alsactl restore
        jack_plugged=$(amixer -c 1 cget numid=1,iface=CARD | awk -F"=" 'NR == 3 {print $2;}')
        if [[ "$jack_plugged" == "on" ]]; then
            amixer -c 1 sset 'Internal Speakers' off
        else
            amixer -c 1 sset 'Internal Speakers' on
        fi

        mkdir -p /var/lib/iwd
        [ -e /boot/iwd ] && cp /boot/iwd/* /var/lib/iwd/
        ;;
    stop)
        brightnessctl -s
        alsactl store
        ;;
    *)
        echo "Usage: $0 {start|stop}"
        exit 1
esac
