#!/bin/sh

start() {
	printf "Starting sway: "
	openvt -s -c 1 -- /usr/bin/sway.sh &
	[ $? = 0 ] && echo "OK" || echo "FAIL"
}
stop() {
	printf "Stopping sway: "
	killall sway
	[ $? = 0 ] && echo "OK" || echo "FAIL"
}
restart() {
	stop
	start
}

case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  restart|reload)
	restart
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

