#!/bin/sh

start() {
	printf "Starting syncthing: "
	# Wait for network to be available
	sleep 5
	/usr/bin/start_syncthing &
	[ $? = 0 ] && echo "OK" || echo "FAIL"
}
stop() {
	printf "Stopping syncthing: "
	killall syncthing
	[ $? = 0 ] && echo "OK" || echo "FAIL"
}
restart() {
	stop
	start
}

case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  restart|reload)
	restart
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac 