################################################################################
#
# LIBRETRO PPSSPP
#
################################################################################

LIBRETRO_PPSSPP_VERSION = 87f7523f995af4a4d348ad222c02a96c0caf6638
LIBRETRO_PPSSPP_SITE = https://github.com/hrydgard/ppsspp
LIBRETRO_PPSSPP_SITE_METHOD=git
LIBRETRO_PPSSPP_GIT_SUBMODULES=y
LIBRETRO_PPSSPP_DEPENDENCIES = libpng snappy mesa3d
LIBRETRO_PPSSPP_LICENSE = GPL-2.0
LIBRETRO_PPSSPP_LICENSE_FILES = LICENSE.TXT

LIBRETRO_PPSSPP_CONF_OPTS += -DCMAKE_C_ARCHIVE_CREATE="<CMAKE_AR> qcs <TARGET> <LINK_FLAGS> <OBJECTS>"
LIBRETRO_PPSSPP_CONF_OPTS += -DCMAKE_C_ARCHIVE_FINISH=true
LIBRETRO_PPSSPP_CONF_OPTS += -DCMAKE_CXX_ARCHIVE_CREATE="<CMAKE_AR> qcs <TARGET> <LINK_FLAGS> <OBJECTS>"
LIBRETRO_PPSSPP_CONF_OPTS += -DCMAKE_CXX_ARCHIVE_FINISH=true
LIBRETRO_PPSSPP_CONF_OPTS += -DCMAKE_AR="$(TARGET_CC)-ar"
LIBRETRO_PPSSPP_CONF_OPTS += -DCMAKE_C_COMPILER="$(TARGET_CC)"
LIBRETRO_PPSSPP_CONF_OPTS += -DCMAKE_CXX_COMPILER="$(TARGET_CXX)"
LIBRETRO_PPSSPP_CONF_OPTS += -DCMAKE_LINKER="$(TARGET_LD)"
LIBRETRO_PPSSPP_CONF_OPTS += -DCMAKE_C_FLAGS="$(TARGET_CFLAGS) -fno-math-errno -DEGL_NO_X11=1 -DMESA_EGL_NO_X11_HEADERS=1"
LIBRETRO_PPSSPP_CONF_OPTS += -DCMAKE_CXX_FLAGS="$(TARGET_CXXFLAGS) -fno-math-errno -DEGL_NO_X11=1 -DMESA_EGL_NO_X11_HEADERS=1"

LIBRETRO_PPSSPP_CONF_OPTS += -DANDROID=OFF
LIBRETRO_PPSSPP_CONF_OPTS += -DAPPLE=OFF
LIBRETRO_PPSSPP_CONF_OPTS += -DARM64=ON
LIBRETRO_PPSSPP_CONF_OPTS += -DBUILD_SHARED_LIBS=OFF
LIBRETRO_PPSSPP_CONF_OPTS += -DCMAKE_BUILD_TYPE=Release
LIBRETRO_PPSSPP_CONF_OPTS += -DCMAKE_SYSTEM_NAME=Linux
LIBRETRO_PPSSPP_CONF_OPTS += -DHEADLESS=OFF
LIBRETRO_PPSSPP_CONF_OPTS += -DLIBRETRO=ON
LIBRETRO_PPSSPP_CONF_OPTS += -DSIMULATOR=OFF
LIBRETRO_PPSSPP_CONF_OPTS += -DUNITTEST=OFF
LIBRETRO_PPSSPP_CONF_OPTS += -DUSE_DISCORD=OFF
LIBRETRO_PPSSPP_CONF_OPTS += -DUSE_MINIUPNPC=OFF
LIBRETRO_PPSSPP_CONF_OPTS += -DUSE_SYSTEM_FFMPEG=OFF
LIBRETRO_PPSSPP_CONF_OPTS += -DUSE_SYSTEM_LIBPNG=ON
LIBRETRO_PPSSPP_CONF_OPTS += -DUSE_SYSTEM_LIBZIP=ON
LIBRETRO_PPSSPP_CONF_OPTS += -DUSE_SYSTEM_SNAPPY=ON
LIBRETRO_PPSSPP_CONF_OPTS += -DUSE_SYSTEM_ZSTD=OFF
LIBRETRO_PPSSPP_CONF_OPTS += -DUSE_VULKAN_DISPLAY_KHR=OFF
LIBRETRO_PPSSPP_CONF_OPTS += -DUSE_WAYLAND_WSI=OFF
LIBRETRO_PPSSPP_CONF_OPTS += -DUSING_EGL=ON
LIBRETRO_PPSSPP_CONF_OPTS += -DUSING_FBDEV=OFF
LIBRETRO_PPSSPP_CONF_OPTS += -DUSING_GLES2=ON
LIBRETRO_PPSSPP_CONF_OPTS += -DUSING_QT_UI=OFF
LIBRETRO_PPSSPP_CONF_OPTS += -DUSING_X11_VULKAN=OFF
LIBRETRO_PPSSPP_CONF_OPTS += -DVULKAN=OFF
LIBRETRO_PPSSPP_CONF_OPTS += -DWIN32=OFF

define LIBRETRO_PPSSPP_INSTALL_TARGET_CMDS
	$(INSTALL) -D $(@D)/lib/ppsspp_libretro.so $(TARGET_DIR)/usr/lib/libretro/ppsspp_libretro.so
	mkdir -p $(TARGET_DIR)/usr/share/ppsspp
	cp -R $(@D)/assets $(TARGET_DIR)/usr/share/ppsspp/PPSSPP
endef

$(eval $(cmake-package))
