name: build brrr

on:
  release:
    types: [published]  # Trigger when a release is published

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      BR_VER: 2024.02.1

    steps:
      - name: Free Disk Space (Ubuntu)
        uses: jlumbroso/free-disk-space@main
        with:
          tool-cache: false

      # Checkout the code
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.release.target_commitish }}

      # Install dependencies
      - name: Install build dependencies
        run: |
          sudo apt-get update && sudo apt-get install -y \
            build-essential curl bc cpio rsync file git wget unzip python3 libssl-dev dosfstools zstd

      # Download and extract Buildroot
      - name: Download and extract Buildroot
        run: |
          mkdir -p ${{ github.workspace }}/workspace
          curl -s -L https://github.com/buildroot/buildroot/archive/refs/tags/${{ env.BR_VER }}.tar.gz | tar xvz -C ./workspace
          ls -l ./workspace/

      # Apply patches and run Buildroot
      - name: Apply patches and build
        run: |
          cd ./workspace/buildroot-${{ env.BR_VER }}
          for i in ${{ github.workspace }}/buildroot*.patch; do patch -p1 < $i; done
          make BR2_EXTERNAL=${{ github.workspace }} rgarc_defconfig
          make -j$(nproc)

      # Copy output to workspace
      - name: Copy output
        run: |
          cp -rv ./workspace/buildroot-${{ env.BR_VER }}/output/images ${{ github.workspace }}/output

      # Upload the output as a release artifact
      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            ./output/brrrrrrrrrr-rgarc.img
            ./output/rockchip/*.*
            ./output/initrd.gz
            ./output/extlinux.conf
